In [2]:
import torch
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
imgs = ['https://ultralytics.com/images/zidane.jpg']  # batch of images

# Inference
results = model(imgs)

# Results
results.print()
results.save()  # or .show()

results.xyxy[0]  # img1 predictions (tensor)
results.pandas().xyxy[0] 

Using cache found in C:\Users\C00488381/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2023-3-16 Python-3.9.13 torch-1.13.1+cpu CPU



  0%|          | 0.00/14.1M [00:00<?, ?B/s]


Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
image 1/1: 720x1280 2 persons, 2 ties
Speed: 295.6ms pre-process, 133.8ms inference, 1.0ms NMS per image at shape (1, 3, 384, 640)
Saved 1 image to runs\detect\exp


xmin        ymin         xmax        ymax  confidence  class    name
0  743.290466   48.343506  1141.756592  720.000000    0.879861      0  person
1  441.989624  437.336670   496.585083  710.036255    0.675119     27     tie
2  123.051056  193.237976   714.690674  719.771362    0.666693      0  person
3  978.989807  313.579529  1025.302856  415.526184    0.261517     27     tie

In [4]:
results.xyxy[0]

tensor([[7.43290e+02, 4.83435e+01, 1.14176e+03, 7.20000e+02, 8.79861e-01, 0.00000e+00],
        [4.41990e+02, 4.37337e+02, 4.96585e+02, 7.10036e+02, 6.75119e-01, 2.70000e+01],
        [1.23051e+02, 1.93238e+02, 7.14691e+02, 7.19771e+02, 6.66693e-01, 0.00000e+00],
        [9.78990e+02, 3.13580e+02, 1.02530e+03, 4.15526e+02, 2.61517e-01, 2.70000e+01]])

In [5]:
results.xyxyn[0][:, -1]

tensor([ 0., 27.,  0., 27.])

In [6]:
results.xyxyn[0][:, :-1]

tensor([[0.58070, 0.06714, 0.89200, 1.00000, 0.87986],
        [0.34530, 0.60741, 0.38796, 0.98616, 0.67512],
        [0.09613, 0.26839, 0.55835, 0.99968, 0.66669],
        [0.76484, 0.43553, 0.80102, 0.57712, 0.26152]])

In [9]:
results.xyxy[0][:, 4]

tensor([0.87986, 0.67512, 0.66669, 0.26152])

In [11]:
results.xyxy[0] [:, 5]

tensor([ 0., 27.,  0., 27.])

In [1]:
print(0.1+0.2)

0.30000000000000004
